# Generated by Django 5.2.4 on 2025-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="availability",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
